### ISSUE TITLE
Where did the repository go?

### ISSUE THREAD

**Issue by SSSAAANNNEEESSSS** [ZelGimi/industrialupgrade#1]
Where did the repository go?

**Comment by Speiger** [comment]
@SSSAAANNNEEESSSS 
Industrial Upgrade was Open sourcing a bunch of closed source mods without permission.

To name the mods in question:
- Uncomplication (entire enet code)
- IC2Classic: Enet code in multiple iterations.
- Ic2 Experimental: audio engine, inventory systems and a bit more.

While copying small parts of code is fine.
Within reason.
But these were entire 1 to 1 copies of big systems.

That was going to far so the mod had to be taken down.

**Comment by SSSAAANNNEEESSSS** [comment]
Oh, I see…
