### ISSUE TITLE
industrial Upgrade 2.4 RC 4 server crash caused by: NoClassDefFoundError: net/minecraft/client/gui/GuiScreen

### ISSUE THREAD

**Issue by Palkia1995** [ZelGimi/industrialupgrade#103]
Mod versions: Industrial Upgrade 2.4 RC 4, industrialcraft 2-2.8.222-ex112
first, your mod is incredible thank you for this mod and your work :D 

i have a custom modpack and today it crashed on my server and i got this crash report, in the meanwhile i use the RC 3 and wait to the next version, so no pressure from my side :D

[crash-2022-07-17_17.16.52-server.txt](https://github.com/ZelGimi/industrialupgrade/files/9128065/crash-2022-07-17_17.16.52-server.txt)

**Comment by ZelGimi** [comment]
use link -> https://www.curseforge.com/minecraft/mc-mods/industrial-upgrade/files/3880008

**Comment by Palkia1995** [comment]
oh that was quick, so but i have another problem, somehow the server is starting but when the world is loading the server is crashing again with this crash on multiple things: 
net/client/util/ITooltipFlag 
ic2 core block TileEntityblock
ic2 core TickHandler on world tick 
at com.denfop.tiles.base.TileEntityBaseSunnariumMaker

and i have removed the things as you stated in the description

[crash-2022-07-17_21.56.46-server.txt](https://github.com/ZelGimi/industrialupgrade/files/9128465/crash-2022-07-17_21.56.46-server.txt)

**Comment by ZelGimi** [comment]
new link: https://www.curseforge.com/minecraft/mc-mods/industrial-upgrade/files/3881459

**Comment by Palkia1995** [comment]
that's awesome your mod is working on my server and these issues are gone now, thank you
