### ISSUE TITLE
bug with digging depth modifier

### ISSUE THREAD

**Issue by idSnail** [ZelGimi/industrialupgrade#104]
When using the dig depth modifier in tools, modes 3 * 3 etc. disappear or partially work on random blocks.
![Screenshot_2](https://user-images.githubusercontent.com/108696380/179419104-9ff4dcdd-fff4-4bb5-b86f-d6130158bc7d.png)

**Comment by ZelGimi** [comment]
Can you record a video?

**Comment by idSnail** [comment]
https://drive.google.com/file/d/1TdZ1sfUkksRkHQVxGC9LYyUhY_C-0k2b/view?usp=sharing

**Comment by ZelGimi** [comment]
fixed, wait RC5

**Comment by ZelGimi** [comment]
fix link: https://www.curseforge.com/minecraft/mc-mods/industrial-upgrade/files/3881459
