### ISSUE TITLE
Language Files of Traditional Chinese

### ISSUE THREAD

**Issue by dxxueer** [ZelGimi/industrialupgrade#109]
I have translate the 1.12.2-2.4_rc4 for Traditional Chinese.
[LanguageFile_TraditionalChinese_1.12.2-2.4_rc4.zip](https://github.com/ZelGimi/industrialupgrade/files/9293385/LanguageFile_TraditionalChinese_1.12.2-2.4_rc4.zip)

**Comment by MakandIv** [comment]
Good, tomorrow (UTC+4) I will add the translation to my repository (the translation from it will be included in the mod). Translation for built-in add-ons will be added separately.
