### ISSUE TITLE
[1.12.2] conductor cannot be linked

### ISSUE THREAD

**Issue by 623667595** [ZelGimi/industrialupgrade#110]
![}{$~GO@H)P6 RA A FB2PZH](https://user-images.githubusercontent.com/88877796/184078297-b60ed06f-cfa6-4a6f-bb94-56ddad019ab0.png)
In the latest beta version, in all the worlds generated by MV multi world plug-ins except the main world, the wires will not be connected, and the machine will not be able to transmit power.

Request emergency repair

**Comment by ZelGimi** [comment]
This is a problem with MV multi word as it doesn't create the world properly (the world doesn't have its own id)
