### ISSUE TITLE
Log Spam when Starting out

### ISSUE THREAD

**Issue by reddvilzz** [ZelGimi/industrialupgrade#111]
I'm using the 2.3.5 version and whenever I add the mod to my modpack 
[this error / spam happen](https://github.com/ZelGimi/industrialupgrade/files/9420348/debug-3.log) and it keeps going on.

Removing the mod fixed the launch, also the minecraft windows will flicker like crazy.

**Comment by ZelGimi** [comment]
This problem is not related to the mod.

**Comment by reddvilzz** [comment]
Okay, thanks.
