### ISSUE TITLE
Missing MFSU

### ISSUE THREAD

**Issue by fxusers** [ZelGimi/industrialupgrade#112]
MFSU disappears when you exit the game. 1.12.2

https://user-images.githubusercontent.com/19208147/187065467-2faf3edb-fd3e-425b-843c-8467c121eb7a.mp4

IC2.ini
; If you really really really don't want to have your machines explode if you don't pay attention to voltage, you can disable that here.
enableEnetExplosions = false

**Comment by ZelGimi** [comment]
f

**Comment by ZelGimi** [comment]
fixed in 2.4RCS5
