### ISSUE TITLE
[1.12.2-RC5] endless loading in 4 stages

### ISSUE THREAD

**Issue by Shonetsu** [ZelGimi/industrialupgrade#113]
Mod infinitely initializes due to more planets?
![3454](https://user-images.githubusercontent.com/112647918/187967252-dabe89aa-df02-40c3-920c-74a6ba0f6f3e.PNG)
[Client thread/wARN]: Inconsistent recipe cache, the entry for the item stevekung.mods.moreplanets.utils.itemblocks.ItemBlockMp@7858ac5f is missing.
[Client thread/wARN]: Inconsistent recipe cache, the entry for the item stevekung.mods.moreplanets.utils.itemblocks.ItemBlockmpe2df6c853 is missing.
[Client thread/wARN]: Inconsistent recipe cache, the entry for the item stevekung.mods.moreplanets.utils.itemblocks.ItemBlockmpe5072c8c6 is missing.
[Client thread/wARN]: Inconsistent recipe cache, the entry for the item stevekung.mods.moreplanets.utils.itemblocks.ItemBlockmpe59c0aa9a is missing.
[Client thread/wARN]: Inconsistent recipe cache, the entry for the item stevekung.mods.moreplanets.utils.itemblocks.ItemBlockmpe34277cba is missing.
Repeats ad infinitum. On the RC4 version, this is not the case.

**Comment by ZelGimi** [comment]
check 2.4RCS5

**Comment by Shonetsu** [comment]
The bug has been fixed. Thank you.
