### ISSUE TITLE
Не Крафтятся Модули в Продвинутом Молекулярном Преобразователе

### ISSUE THREAD

**Issue by HIKAM0RI** [ZelGimi/industrialupgrade#116]
Уже давненько создал сборку для себя с IU версии 2.3.5 Решил не обновляться, ибо боюсь что много чего может сломаться, да и привык уже к ней. В общем проблема в том, что Модули по типу Утро, День, Вечер или Второе Солнце (с другими не проверял) не хотят превращаться во второй и третий уровень (3-й проверял в креативе) в продвинутом молекулярном преобразователе. Как это фиксануть?

**Comment by MakandIv** [comment]
Можно скрин, как выложен рецепт в продвинутом МП?

**Comment by HIKAM0RI** [comment]
![image](https://user-images.githubusercontent.com/113927282/191073613-fee43c23-fe70-4ba7-b609-c34fb2a5cf09.png)
Доходит до 100% и не выдает результата

**Comment by MakandIv** [comment]
Попробуйте сменить режим работы (левая кнопка сверху). И это ошибка была исправлена в более новых версиях, поэтому эта тема будет закрыта.

**Comment by HIKAM0RI** [comment]
Спасибо за помощь, смена режима помогла.
