### ISSUE TITLE
Recipe bug with Forge Hammer (UniDict problem?)

### ISSUE THREAD

**Issue by Xname7** [ZelGimi/industrialupgrade#117]
I tried making Silver Plates using Forge Hammer from IC2 and it didn't work. It doesn't work with any plates from this mod (tried with Zinc as well)
When i made a fresh Forge Hammer the recipe worked once and then it didn't
First screenshot is without UniDict installed and it works like it should
On next screenshots i have UniDict installed and it doesn't work
Last one shows how the recipe looks in JEI
![image](https://user-images.githubusercontent.com/66174882/191701426-93f82d65-9f0b-4d49-9e43-266247680a36.png)
![image](https://user-images.githubusercontent.com/66174882/191703788-11437e84-f55f-4e06-b8ea-576ac9e748db.png)
![image](https://user-images.githubusercontent.com/66174882/191704560-a094c6e4-8cbd-400d-a0ef-b20bb099a80f.png)
![image](https://user-images.githubusercontent.com/66174882/191703926-f6334d29-07ce-430a-8617-e41e0213b249.png)

**Comment by ZelGimi** [comment]
fix
