### ISSUE TITLE
Liquid matter generator not working properly

### ISSUE THREAD

**Issue by BoomEaro** [ZelGimi/industrialupgrade#121]
Industrial upgrade: 1.12.2-2.4RC6
Industrial craft 2: 2.8.222-ex112

1. Disabled liquid matter generator continues to consume energy.
2. Scrapboxes or scrap cannot be placed using hoppers.
3. Generator cannot be switched using redstone signal (Redstone signal not connecting to block), it seems not only this block has such a problem.

**Comment by ZelGimi** [comment]
fixed
