### ISSUE TITLE
Some strange problems with the reactor

### ISSUE THREAD

**Issue by BoomEaro** [ZelGimi/industrialupgrade#122]
Industrial upgrade: 1.12.2-2.4RC6
Industrial craft 2: 2.8.222-ex112

1. Reactor cannot be switched with redstone (redstone block does not connect).
2. With some chance, when the fuel rod is depleted, the reactor can produce permanently strange eu/t output values, and these are real eu/t. This state is corrected if any other element in the reactor was removed and then returned back.
3. A very strange and floating bug, when installing a reactor and adding all 6 cameras, the reactor considers that it still does not have these cameras, which is why it is impossible using hoppers (or another mod) to add or remove elements beyond 35 slots.
In single player, I personally could not reproduce this bug, it occurs on the server, but even there it is difficult to try to reproduce it constantly.
This seems to fix itself when the chunk is reloaded when the player moves too far away.
4. Improved and higher reactors do not destroy the territory after the explosion, but disappear themselves.

**Comment by BoomEaro** [comment]
> 1. The redstone system has also been removed
> 2. can you send a video?
> 3. it means there is some plugin or mod that does optimization on the server
> 4. by default they do not break, you can enable explosions in the config

Oh, I'm sorry I didn't say right away, I'm using a regular vanilla forge server (not some kind of mohist or something like that), it seems to me that I don't have a single mod that could optimize something, but maybe I'm wrong.

As I said above, sometimes when installing new cameras in the reactor, as I understand it, the inventory of the tile entity does not update correctly, because hoppers or other entities cannot add or take items further than the parent size of the reactor that was installed.
At the moment when such a bug happened, I was checking the reactor from the usual industrial craft 2 and it was stacking the elements correctly, I will try to experiment with this further and tell you.

As for the fuel rods. Unfortunately, for now I have to take my word for it, because in order to deplete the rod, I need to spend 8000 seconds of time (for example, for a curium rod) to capture this moment, but I can now give more details.
The output eu/t constantly changes from each such rod at the moment of its depletion and remains until the element has been rearranged. In theory, this means that depleted rods can give out a huge amount of free eu/t.
This, on the other hand, can greatly reduce the output eu/t.

I will try to capture this moment and show you.

**Comment by BoomEaro** [comment]
Bug with rods:
https://www.youtube.com/watch?v=3RLFlsgph4w

Bug with reactor inventory:
https://www.youtube.com/watch?v=a62zU7yoSIs
I forgot to also say that this only happens with industrial upgrade reactors (on the video I will show how a regular reactor works in the same place)

**Comment by ZelGimi** [comment]
Fixed the bugs that are indicated in the video
