### ISSUE TITLE
Many devices that should use a redstone signal do not use it

### ISSUE THREAD

**Issue by BoomEaro** [ZelGimi/industrialupgrade#124]
Industrial upgrade: 1.12.2-2.4RC6
Industrial craft 2: 2.8.222-ex112

1. This is rather strange and it is not clear whether this was originally intended, but devices such as a reactor, any energy storage unit, a liquid matter generator and other similar units cannot be configured using a redstone signal. Redstone does not connect to them, which makes it impossible to create automation.
2. Any energy storage in a regular industrial craft 2 could be configured to emit a redstone signal, however this button is not present for the new storages from industrial upgrade.

**Comment by ZelGimi** [comment]
Were forced to remove redstone support, due to excessive load with a large number of mechanisms.

**Comment by BoomEaro** [comment]
> Were forced to remove redstone support, due to excessive load with a large number of mechanisms.

Oh, that's sad to hear.
Does this also apply to the ability to customize the output of the redstone signal from the energy store?
It’s just that such an opportunity was really very useful and until that moment I always thought that this was a bug or just not fully implemented functionality)

**Comment by ZelGimi** [comment]
Added redstone signal capability in 2.5
