### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Wy9Aready** [ZelGimi/industrialupgrade#127]
When I play your mod in creative mode，There may be rendering vulnerabilities in the lastest mod version.There is the crash report
![QQ图片20230105184639](https://user-images.githubusercontent.com/122018664/210762393-26ee6d5c-0a16-467e-91a3-9fa79d0c6f26.jpg)

**Comment by ZelGimi** [comment]
In this screenshot, there is no problem through IU.

**Comment by MakandIv** [comment]
You need a full crashlog file. On the presented information, IU does not appear at all.

**Comment by Wy9Aready** [comment]
thanks
