### ISSUE TITLE
Molecular recipes issue with CraftTweaker

### ISSUE THREAD

**Issue by the-darkkk** [ZelGimi/industrialupgrade#128]
While trying to add molecular recipes as in #50 , 
`mods.industrialupgrade.MolecularTransformer.addRecipe(IItemStack output, IIngredient ingredient, energy);`
my receipes :
`mods.industrialupgrade.MolecularTransformer.addRecipe(<minecraft:redstone_block>, <ore:WoolRed>, 30000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<minecraft:gold_block>, <ore:WoolOrange>, 10000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<minecraft:glowstone>, <ore:WoolYellow>, 5000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<minecraft:lapis_block>, <ore:WoolBlue>, 5000000);`
and i'm getting this error and no recipes added
![image](https://user-images.githubusercontent.com/92176347/210797086-4bcc45ae-2668-4958-bcdd-5108216fdd0b.png)

industrial upgrade version 2.4 beta (11/5/22), CraftTweaker version CraftTweaker2-1.12-4.1.20.682.jar (latest), mc 1.12.2

**Comment by ZelGimi** [comment]
need modweaker

**Comment by the-darkkk** [comment]
> need modweaker

ok, now next issue
when installing modtweaker (and mtlib) all molecular receipes just disappear (even default ones)

**Comment by ZelGimi** [comment]
So some mod removes them or a script

**Comment by ZelGimi** [comment]
These mods have been standing for a long time and I always check and everything works fine

**Comment by the-darkkk** [comment]
Thank's for reply, fixed it
The solution was to change <ore:Wool(Colour)> to <minecraft:wool:(id)>

**Comment by the-darkkk** [comment]
Thank's for reply, fixed it
The solution was to change <ore:Wool(Colour)> to <minecraft:wool:(id)>
