### ISSUE TITLE
Not compatible with Draconic-Evolution

### ISSUE THREAD

**Issue by Rambo28456** [ZelGimi/industrialupgrade#132]
Version mod - Draconic-Evolution-1.12.2-2.3.28.354-universal
Version mod - IndustrialUpgrade-1.12.2-2.4.0.9

1. Dragon Flux Capacitor has stopped charging the Electric Key.
2. Wires do not connect to Injector merges.
3. Wires do not connect to the weather controller

![Снимок экрана (51)](https://user-images.githubusercontent.com/108591561/212462434-64633a99-ecd4-483a-a8ab-3e172979ab37.png)

**Comment by ZelGimi** [comment]
rearrange the mechanism
