### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [ZelGimi/industrialupgrade#133]
[crash-2023-01-23_13.34.06-client.txt](https://github.com/ZelGimi/industrialupgrade/files/10479698/crash-2023-01-23_13.34.06-client.txt)

**Comment by kasia1403-is-a-stupid-retard** [comment]
You never learn from your mistakes, do you dumbass?

**Comment by ZelGimi** [comment]
Specify the version of the mod, this error can happen in the wrong use of the mod config

**Comment by ZelGimi** [comment]
And you need to be patient, I currently have 3-5 hours of electricity in my region
