### ISSUE TITLE
Problems with crafting plates and sticks from the mod itself Industrial Upgrade 1.7.10

### ISSUE THREAD

**Issue by Denis6781** [ZelGimi/industrialupgrade#134]
Crafting is completely absent. Mod version Industrial Upgrade 1.7.10 2.5.20-2.5.21.
I collect the mod from the sources on your site, since you don't have a ready one, and I didn't want to take it from other sites

![IU](https://user-images.githubusercontent.com/65903339/214078079-55beca2e-17cc-4b25-b3e7-68449eeeab04.png)

**Comment by ZelGimi** [comment]
Use 2.5.17
