### ISSUE TITLE
Дюп Bonsai Pot'ов

### ISSUE THREAD

**Issue by Serega007RU** [ZelGimi/industrialupgrade#137]
Всё полностью показано в данном видео https://youtu.be/gxTuONyYcNk?t=233
Ссылка с таймкодом но всё же и тут укажу таймкоды, смотреть с 3:53 по 5:10

Проверял Industrial Upgrade версии 2.4.0.16, дюп работает

**Comment by ZelGimi** [comment]
Посмотрел данный мода код, ужаснулся, что разраб натыкал в метод где просто ломается дроп, ещё и спавн его вещей, и вышло что у него два метода на выкидание вещей, что сказать разраб мода вообще не знает использование метода, пофиксим такое недорозумение для тех "разрабов"

**Comment by ZelGimi** [comment]
Решили
