### ISSUE TITLE
proton solar panel crash

### ISSUE THREAD

**Issue by ASKet12** [ZelGimi/industrialupgrade#138]
when installing a proton solar panel to the BC pump, the world brightened up :(
[crash-2023-02-10_13.59.41-server.txt](https://github.com/ZelGimi/industrialupgrade/files/10725061/crash-2023-02-10_13.59.41-server.txt)

**Comment by ZelGimi** [comment]
at com.kingrunes.somnia.common.util.SomniaUtil.tick(SomniaUtil.java:137), problem with https://www.curseforge.com/minecraft/mc-mods/somnia/files

**Comment by ASKet12** [comment]
> at com.kingrunes.somnia.common.util.SomniaUtil.tick(SomniaUtil.java:137), problem with https://www.curseforge.com/minecraft/mc-mods/somnia/files

![image](https://user-images.githubusercontent.com/125302330/218552332-79cdb28e-b773-4c70-886c-0338a4af0e20.png)

**Comment by ASKet12** [comment]
> at com.kingrunes.somnia.common.util.SomniaUtil.tick(SomniaUtil.java:137), problem with https://www.curseforge.com/minecraft/mc-mods/somnia/files

Well, I did a complete rebuild of my modpack adding each mod in turn, however strange it may seem, everything worked, I apologize, the topic can be closed.
