### ISSUE TITLE
Problem with AE

### ISSUE THREAD

**Issue by Defflorstor** [ZelGimi/industrialupgrade#14]
So, now, when IU uses ne energy system, how I can to power up Applied Energistics storage? Wires can not longer connect
![Screenshot_1](https://github.com/ZelGimi/industrialupgrade/assets/67242805/6f52b15d-63eb-4a1a-91e5-b79cc0b9d441)

**Comment by ZelGimi** [comment]
use Power Utilities

**Comment by Defflorstor** [comment]
Kk, thx
