### ISSUE TITLE
Crashing, can`t launch game.

### ISSUE THREAD

**Issue by Defflorstor** [ZelGimi/industrialupgrade#142]
After 2.4.0.16 version it become crushing. Up to version 16, everything worked perfectly, and starting from it and up to version 17, the game does not even start. There is a crash log below.

[crash-2023-02-20_20.24.16-client.txt](https://github.com/ZelGimi/industrialupgrade/files/10787595/crash-2023-02-20_20.24.16-client.txt)

**Comment by ZelGimi** [comment]
All addons have an update for IU 2.4.0.17, update them

**Comment by Defflorstor** [comment]
kk, will try

**Comment by Defflorstor** [comment]
Ok, so the reason was this mod. But, then how to get QE for quantum quarry?

**Comment by Defflorstor** [comment]
Oh, it`s got updated too. Ok, thx anyway)
