### ISSUE TITLE
Can`t stack wither skulls and blade assembler blades.

### ISSUE THREAD

**Issue by Defflorstor** [ZelGimi/industrialupgrade#144]
So I have like 650 skulls and soul sand rn, but I should put it all by 1 and it`s really annoying, same with blade assembler. Can you make in like before stackable again?
![Screenshot_2](https://user-images.githubusercontent.com/67242805/220420902-04eb22c2-e5f4-4b3f-868f-3d9c3d838306.png)
![Screenshot_3](https://user-images.githubusercontent.com/67242805/220420906-fa64907c-dbc1-41f9-9f69-e04ae64c1d36.png)

**Comment by ZelGimi** [comment]
If it stacks, the autocraft will break
