### ISSUE TITLE
Are you alive?

### ISSUE THREAD

**Issue by Defflorstor** [ZelGimi/industrialupgrade#147]
Hey, just wondering how are you? For a long time no new updates have been released, so for some reason, version 17 was deleted immediately after the release (by the way, 16 crashes, but 17 does not). We are all looking forward to new updates, come back)

**Comment by ZelGimi** [comment]
Post the crash log

**Comment by ZelGimi** [comment]
Perhaps you are using those versions of the mod and addon that have been removed, check the versions on the curseforge
