### ISSUE TITLE
Language file for zh_TW

### ISSUE THREAD

**Issue by dxxueer** [ZelGimi/industrialupgrade#149]
I have update the language for 2.4.0.16.
I'm sorry for so late.
https://1drv.ms/u/s!AuyeYIg5lTml1CUFPk87UKAw4oqh

**Comment by oiiishoo** [comment]
link is unavailable, load the file on mediafire/dropbox/like these

**Comment by dxxueer** [comment]
Sure.
https://www.mediafire.com/file/wthz9m6k4cmhjt1/lang_zh_TW_1.12.2-2.4.0.16.zip/file

**Comment by MakandIv** [comment]
Hello, I have added updated file in [repository](https://github.com/MakandIv/industrial-upgrade-localizations). The repository contains the latest versions, including fixes for mistakes that accidentally got into the mod, and localization of items, blocks, etc. that are expected in the new version, in the future you can see the changes there to update the localization.

**Comment by dxxueer** [comment]
I see，thank you.
