### ISSUE TITLE
Интеграция с Applied Energistics

### ISSUE THREAD

**Issue by megboyzz** [ZelGimi/industrialupgrade#15]
Планируется ли интеграция с AE2?

**Comment by ZelGimi** [comment]
Это не от меня зависит , п зависит от разработчика ае2, так как он делал интеграции с другими энергиями

**Comment by megboyzz** [comment]
Ну насколько я помню версией раньше, провода  из ui подключились без проблем к механизмам из ae, а сейчас нет, грустно
