### ISSUE TITLE
Dupe 

### ISSUE THREAD

**Issue by RomanDzhan** [ZelGimi/industrialupgrade#150]
Працює зі всіма ресурсами. Ось посилання  https://youtu.be/L5Vmxu-T_Bg
Версія моду IndustrialUpgrade-2.5.21.jar.

**Comment by ZelGimi** [comment]
прикольна річ

**Comment by RomanDzhan** [comment]
Скажіть якщо не важко?

**Comment by ZelGimi** [comment]
Disassembled the issue in the Discord server
