### ISSUE TITLE
Problem with the "quarry vein item" (Drilling Rig)

### ISSUE THREAD

**Issue by Elendron** [ZelGimi/industrialupgrade#152]
The problem is that if, after the rig finds an oil or mineral vein, it exits the game, then when it returns, it is reset, and almost always the chunk becomes empty. Can you tell me why this is happening?

**Comment by ZelGimi** [comment]
This happens when the vein is in the chunk for the first time, data remains on the next restart of the world, how to solve this problem (autocorrect on the first restart when the vein is found) I don’t know, maybe the problem is creating data on exit

**Comment by Elendron** [comment]
Hi! I understood why this is happening. The chunk is rebooted with those chunks that are not loaded by the "Chunk Loader" from Industrial Craft. Maybe this will help others solve the problem.

**Comment by ZelGimi** [comment]
This problem was solved in 2.5.0.4, it says that saving a fix

**Comment by Elendron** [comment]
OOO Thank you very much!
