### ISSUE TITLE
Version 2.5 does not start on the server

### ISSUE THREAD

**Issue by Anemonky** [ZelGimi/industrialupgrade#154]
[crash-2023-05-04_18.51.32-server.txt](https://github.com/ZelGimi/industrialupgrade/files/11400680/crash-2023-05-04_18.51.32-server.txt)

If I understand correctly, minecraft treats the new version as a client mod. Can you fix this please? Everything works in single.

**Comment by ZelGimi** [comment]
will be fixed

**Comment by Anemonky** [comment]
Great, thanks!
