### ISSUE TITLE
Не выпадают звёзды незера в автоматическом охотнике

### ISSUE THREAD

**Issue by Rambo28456** [ZelGimi/industrialupgrade#155]
Версия мода IndustrialUpgrade-2.5
Полгода назад, не помню в какой версии все работало через "Охотничий модуль - Визер"

**Comment by ZelGimi** [comment]
Боссов давно нельзя в автоохотник класть

**Comment by ZelGimi** [comment]
Можно увеличить количество холодильников и соединить трубами
