### ISSUE TITLE
Simply Quarries 1.6.1 startup crash

### ISSUE THREAD

**Issue by Smukie** [ZelGimi/industrialupgrade#160]
Hello, first of all, I apologize if this is not the correct place to start a bug report for the "Simply Quarries" mod. I could not find any other place to report the problem.

It started crashing after updating its mods to the latest version. The modpack works again if I roll back all the updates to the mods listed below:

"IndustrialUpgrade-1.12.2-2.5.0.4"
"Power+Utilities 1.5.3"
"wireless-industry-1.1.22-release"
"Quantum Generators 1.3.1"

crash report below.
[crash-2023-05-07_20.00.44-client.txt](https://github.com/ZelGimi/industrialupgrade/files/11416170/crash-2023-05-07_20.00.44-client.txt)

**Comment by ZelGimi** [comment]
Fixed, use Simply Quarries 1.6.2
