### ISSUE TITLE
Where is EU

### ISSUE THREAD

**Issue by Elendron** [ZelGimi/industrialupgrade#161]
From the moment the mod became full-fledged, I can't feed the mechanisms that require EU with new wires. For example, a chunk loader. Are you planning to add an alternative to this mechanism?

**Comment by ZelGimi** [comment]
For now, I suggest using https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8

**Comment by Elendron** [comment]
Thanks! Are you planning to make your own version of the mechanism in the future?

**Comment by ZelGimi** [comment]
yes

**Comment by ZelGimi** [comment]
there will be a unique mod already independent of ic2, Industrial Modern

**Comment by Elendron** [comment]
Sounds just great!
