### ISSUE TITLE
auto-crafts from applied energistics do not work with batteries

### ISSUE THREAD

**Issue by mars887** [ZelGimi/industrialupgrade#163]
version - 2.5.0.6
Any autocraft in which the battery is used freezes. 
![2023-05-09_11-26-42](https://user-images.githubusercontent.com/80640750/237039954-f1720070-1e0f-4140-90f7-a219956e51bd.png)
But in a normal workbench everything works.
when crafting, it creates new batteries even if they are available

**Comment by ZelGimi** [comment]
ae2 official?

**Comment by mars887** [comment]
yes

**Comment by ZelGimi** [comment]
use ae2 unofficial

**Comment by ZelGimi** [comment]
https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life

**Comment by mars887** [comment]
now everything works. thanks
