### ISSUE TITLE
Energy Crystals

### ISSUE THREAD

**Issue by Elendron** [ZelGimi/industrialupgrade#164]
after updating to the latest version, I noticed that the crafting of crystals is broken. It's like it's loaded, but it's not. Please fix it. There's something similar to the crafting of coal dust, I suppose. By the way, can I ask if you speak Russian?
![ApplicationFrameHost_wIa52xRfP8](https://github.com/ZelGimi/industrialupgrade/assets/131674843/15eed4ac-d3d0-4505-8800-1624e7b86050)
![ApplicationFrameHost_i7oeaOlU4W](https://github.com/ZelGimi/industrialupgrade/assets/131674843/5be366e4-fa14-49a0-a076-0c6c86356101)

**Comment by ZelGimi** [comment]
this problem is not on my side
