### ISSUE TITLE
в крафте se датчика используется бронзовая пластина из индастриала которая не имеет нормального крафта

### ISSUE THREAD

**Issue by mars887** [ZelGimi/industrialupgrade#165]
если сложить молот и бр.слиток получается пластина из термала
а в крафте требует именно из индастриала

![Minecraft 1 12 2 12 05 2023 18_59_27](https://github.com/ZelGimi/industrialupgrade/assets/80640750/1a77afc1-82d7-4091-b850-a01fe160ac0b)
![Minecraft 1 12 2 12 05 2023 18_59_12](https://github.com/ZelGimi/industrialupgrade/assets/80640750/8d398fbe-d2d2-4b88-b565-28890a239776)

**Comment by ZelGimi** [comment]
Пофикшено
