### ISSUE TITLE
Проблемы с модулем беспроводной связи

### ISSUE THREAD

**Issue by Rambo28456** [ZelGimi/industrialupgrade#166]
В режиме хранилища не удается сохранить координаты самого хранилища.
Я попробовал в режиме панели сохранить координаты, все получилось, но когда перевел в режим хранилища то энергия не передается.
Версия мода - IndustrialUpgrade-1.12.2-2.5.0.6

**Comment by Rambo28456** [comment]
И не могу понять почему когда создаю шаблон на крафт, то вместо пластин из IU туда попадают пластины из Thermal Foundation, хотя намеренно выбираю на пластины из мода IU (через Shift).
![image](https://github.com/ZelGimi/industrialupgrade/assets/108591561/84839217-a6eb-4d51-a813-7b12f6bd9aaa)
И ещё в разных версиях мода Industrial Upgrade прокатный станок делает из любых слитков, пластины из Thermal Foundation (те пластины которые похожие между друг другом из этих модов). Не помню в каких версиях IU такое было, но сейчас опять вернулось.

**Comment by ZelGimi** [comment]
В режиме хранилища не удается сохранить координаты самого хранилища. Так как режим хранилища, а не панели, сохранять данные хранилища в его режиме никак

**Comment by ZelGimi** [comment]
по поводу пластин, не понимаю суть

**Comment by Rambo28456** [comment]
> В хранилище неиспользованные ресурсы сохранения самого хранилища. Так как режим хранилища, а не панели, хранилища данных в его режиме никак

То есть передавать энергию с одного мфсу в другое мфсу уже нельзя?

**Comment by Rambo28456** [comment]
> по поводу пластин, не понимаю суть

В какой то версии IU, механизм прокатный станок делал из слитков пластины из IC2. У меня даже автокрафт сохранился
![image](https://github.com/ZelGimi/industrialupgrade/assets/108591561/a283c375-fdb7-436e-b050-7274b7a6aa82)

А теперь прокатный станок делает из слитков пластины из мода Thermal Foundation
![image](https://github.com/ZelGimi/industrialupgrade/assets/108591561/d834ed38-cf95-485b-a588-683c8db59c15)

И в итоге автокрафт не принимает те пластины которые сейчас производятся, они как бы в самом крафте одинаковые, но автокрафт не видит схожесть.
В разных версиях IU было по разному, раньше прокатный станок делал пластины из мода IC2.
Как сделать так что бы прокатный станок делал пластины из IC2? Не удаляя сам Thermal Foundation

**Comment by ZelGimi** [comment]
удалите UniDict

**Comment by ZelGimi** [comment]
и можно передавать с одного хранилища в другое, меняете режим на панель, пкм по хранилищу который будет получаетелем, меняете режим и модуль в хранилище отправителя

**Comment by Rambo28456** [comment]
> удалите UniDict

Этот мод раньше стоял, убрал уже давненько из-за бесполезности.
По логике, прокатный станок должен делать пластины из IC2, верно?

**Comment by ZelGimi** [comment]
По поводу пластин решено в обнове
