### ISSUE TITLE
Gas/Diesel/Hydrogen Generator accepting fluid to generate energy

### ISSUE THREAD

**Issue by theTyrfing** [ZelGimi/industrialupgrade#170]
■Mod version
IndustrialUpgrade-1.12.2-2.5.0.10.jar

■ Singleplayer or server?
Singleplayer

■ Describe the bug
Gas/Diesel/Hydrogen Generators accepts any fluid when it should not.

■ To Reproduce
1) Place any of the above machines
2) Get bucket of water
3) Put bucket into machine
4) Machine generates power

■ Expected behavior
Accepts the appropriate liquid to generate energy

■ Crash Report
None

**Comment by ZelGimi** [comment]
thank you, fixed, will be 2.5.0.11 wait
