### ISSUE TITLE
Applied Energetics support

### ISSUE THREAD

**Issue by sollosollo4** [ZelGimi/industrialupgrade#171]
Industrial craft 2 mod that supports AE (including energy) by default. The Industrial Upgrade does not connect the wires from IC2 to the IU. This causes problems with integrations. Should we wait for integration with AE2?

**Comment by ZelGimi** [comment]
Direct integration cannot be done in any way, it was, but through the shortfalls of the chunk system, it was removed. Integration to FE is. Use power sources with AE2
