### ISSUE TITLE
Вопрос: как получить сталь?

### ISSUE THREAD

**Issue by lightness** [ZelGimi/industrialupgrade#172]
Прошу прощения за глупый вопрос, но как получить сталь?

Насколько я понимаю есть два пути:
1. завод сплавов
2. доменная печь (конструкция 3х3х3)

Разбирает варианты:
1. Для завода сплавов нужна сталь (Датчик: Сплав требует 2 плотные стальные пластины) - Не вариант 
2. Для доменной печи все блоки крафтятся кроме жидкостного блока доменной печи. Для него нужен наполнитель. Для наполнителя нужен Датчик: Наполнение. Для Датчика: Наполнение нужно 2 шестерни из мунц-металла. Которые соответсвенно делаются из мунц-металла, который можно получить толькл в улучшенном заводе сплавов. Для улучшенного завода сплавов нужен Завод сплавов. А его мы построить не можем (см п.1)

Что я упускаю? может JEI не показывает какой-то рецепт?

**Comment by ZelGimi** [comment]
Обновите мод до последней версии

**Comment by ZelGimi** [comment]
у вас старая версия

**Comment by lightness** [comment]
Большое спасибо!
