### ISSUE TITLE
Ветровая энергия

### ISSUE THREAD

**Issue by vasaeps3** [ZelGimi/industrialupgrade#173]
Добрый день
Подскажите пожалуйста, нет ли ошибки в рецепце создания "Датчик: ветер" или "Сжатая иридиевая пластина" 
Для сжатой иридиевой пластины необходима иридиевая руда из IC2 которая добывается с помощью молекулярного преобразователя
![1](https://github.com/ZelGimi/industrialupgrade/assets/4850895/6fbbb5d8-8c26-482b-9be7-b679da940319)
![2](https://github.com/ZelGimi/industrialupgrade/assets/4850895/f79bc1a0-6362-4883-87ff-f1d7a09819c4)
![3](https://github.com/ZelGimi/industrialupgrade/assets/4850895/1c3c5c4e-37b8-4e78-b1e4-45cd711757eb)

Выглядит так будто ветровая энергия станет доступна чуть ли не в конце виживания.

Спасибо

**Comment by ZelGimi** [comment]
В середине выживания
