### ISSUE TITLE
Cannot craft OD scanner from IC2

### ISSUE THREAD

**Issue by Gradess2019** [ZelGimi/industrialupgrade#174]
There is a OD scanner in IC2 and it uses IC2 copper cables, but with this mode I can make copper cables from Industrial Upgrade, therefore it is impossible to craft this scanner.
Is there any way I can convert Industrial Upgrade copper cables to IC2 ones?

MC version: 1.12.2
Mod version: 2.5.0.15

![image](https://github.com/ZelGimi/industrialupgrade/assets/38568823/ca03b70d-3db2-47f6-b883-01e443a5c058)
![image](https://github.com/ZelGimi/industrialupgrade/assets/38568823/15db8b20-4cfc-4a89-baa2-371383266dd8)
![image](https://github.com/ZelGimi/industrialupgrade/assets/38568823/4905e1d6-4baa-4273-956f-c756993eb8b2)

**Comment by ZelGimi** [comment]
Added your own craft of these items
