### ISSUE TITLE
The problem with energy storage

### ISSUE THREAD

**Issue by Shelq27** [ZelGimi/industrialupgrade#175]
Нет отображения RF энергии в хранилище
![image](https://github.com/ZelGimi/industrialupgrade/assets/112713576/2ebf18c8-fb67-489d-a10d-db47dc8c767a)
также RF  модуль не устанавливается  в хранилище во все типы и мфэ и мфсу

**Comment by ZelGimi** [comment]
в измененияї версии, было указано что ушли с RF/FE

**Comment by BLauncher** [comment]
> в изменениях версии, было указано что ушли с RF/FE

Можно узнать почему ? Было очень удобно использовать это

**Comment by ZelGimi** [comment]
есть конвертеры

**Comment by ZelGimi** [comment]
Прикол в том что в каждом моде своя реализация FE/RF, особенно разраб термала который болт клал на своё апи если труба бесконечная

**Comment by ZelGimi** [comment]
и фиксил только я добавляя костыли в свой мод

**Comment by ZelGimi** [comment]
и когда в каждого мода по своей фиче я просто взял и удалил её
