### ISSUE TITLE
Некорректная работа Улучшения "Трансформатор"

### ISSUE THREAD

**Issue by BLauncher** [ZelGimi/industrialupgrade#177]
После того как вынимаешь улучшения механизм не взрывается и можно положить ускорителей.
Залил видос, чтобы понятнее было
https://www.youtube.com/watch?v=5uA-He53ENg

**Comment by ZelGimi** [comment]
Логика работает нормально так как считается уровень по проводящей энергии, а не к источника, по старой ик2 системе если источник имеет 14 уровень а проводит 1 еу, то механизм с 1 уровнем который хранит 30 еу должен бабахать, кнш нет.
Через это пофиг на источник, главное передача, уровень источника означает только макс передачу не более

**Comment by ZelGimi** [comment]
Так что бага нет

**Comment by ZelGimi** [comment]
если 14 уровень будет передавать например 33 еу, а 1 уровень будет хранить 40 еу, то он бабахнет и правильно

**Comment by BLauncher** [comment]
> если 14 уровень будет передавать например 33 еу, а 1 уровень будет хранить 40 еу, то он бабахнет и правильно

https://www.youtube.com/watch?v=0kkOjYVTgtY
почему не ложится улучшение ?

**Comment by ZelGimi** [comment]
С креатива выйти нужно и два раза по слоту
