### ISSUE TITLE
проблема с холодильником

### ISSUE THREAD

**Issue by steven688v2** [ZelGimi/industrialupgrade#179]
![image](https://github.com/ZelGimi/industrialupgrade/assets/140270995/2d700cd5-605c-4a42-a7e7-7aaacafbc679)
холодильник после перезахода в игру перестаёт работать энергия к нему не подходит и кроме как скрафтить новый ничего другое не помогает

**Comment by ZelGimi** [comment]
У вас есть моды на время суток? Или включён бесконечный день? Достаточно энергии? К источнику энергии подключены много механизмов? Если да, то какие? Проверяли ли вы этот баг в другом мире? 
Покажите видео как происходит баг

**Comment by steven688v2** [comment]
стоит мод на длинный день Longer day или как то так называется 
был подключен к 4 улуч печкам и 4 улуч дробителям по 1 ускору в каждой и подключены по квантовой охлаждающей трубе,я заметил этот баг случается когда я перехожу из мира в мир постараюсь записать видео или это проблема заключается в моде на время суток ?

**Comment by ZelGimi** [comment]
Да, с модами на длительность суток, там расчёт тиков мира другой и через это страдают механизмы

**Comment by steven688v2** [comment]
понял удалю посмотрю решиться проблема или нет если что отпишу спасибо за помощь <3

**Comment by steven688v2** [comment]
вот видео звук прибора есть но не генерирует азот 

https://github.com/ZelGimi/industrialupgrade/assets/140270995/22cdd829-7991-47fa-b2bd-5e9a26f83049

**Comment by steven688v2** [comment]
короче тема закрыта виновен был мод longer day даже когда я его удалил он оставил настройки длинного дня я понял шо день всё ровно длинный по облакам xD 300IQ
я всё не мог понять почему холодильник то работал то нет и пришёл к выводу что надо заново поставить этот мод поставить время на стандарт и снова снести и чудо всё заработало воздуха разделительная машина реал очень багованная то по проводам не хочет подключаться то азот вырабатывать не хочет энивей спасибо за помощь и извини за беспокойство <3
