### ISSUE TITLE
Проблема с холодильником и нагревателем

### ISSUE THREAD

**Issue by Defflorstor** [ZelGimi/industrialupgrade#18]
Дело в том, что холодильник почему то даже на -64 градусах не хочет охлаждать механизмы, например сжиматель, хотя энергия есть.

![1](https://github.com/ZelGimi/industrialupgrade/assets/67242805/708d88fc-ca8f-4e81-aeac-96b535776cca)
![2](https://github.com/ZelGimi/industrialupgrade/assets/67242805/c3b7156b-687e-43b3-80b1-a0322525e10a)

Так же, только наоборот, почему то несмотря на то, что жидкостный нагреватель полностью рабочий, термальная центрифуга не хочет работать. Так же заметил, что в описании блока написано, что его нужно охлаждать, но в интерфейсе написано наоборот - то, что его нужно охлаждать.

![3](https://github.com/ZelGimi/industrialupgrade/assets/67242805/fa1421b9-37d3-4b9b-9186-3fac53f2d1a4)
![4](https://github.com/ZelGimi/industrialupgrade/assets/67242805/6734aa98-deb6-473b-8ad7-80e76853e138)
![5](https://github.com/ZelGimi/industrialupgrade/assets/67242805/99bc6e25-fea2-48c2-8675-6df830bedde7)
![6](https://github.com/ZelGimi/industrialupgrade/assets/67242805/73cac132-5140-4d51-8a4b-be31760181b0)
![7](https://github.com/ZelGimi/industrialupgrade/assets/67242805/8ff3ac2a-7936-4d95-af63-322a23bed3b4)

Прошу пожалуйста помощи :(

**Comment by ZelGimi** [comment]
У вас стоит мод на бесконечный день или большой день?

**Comment by Defflorstor** [comment]
Да, вводил doDayCycle false, в этом дело?

**Comment by ZelGimi** [comment]
да

**Comment by Defflorstor** [comment]
Спасибо, помогло! 

P.S. - Очень жду обновления(
