### ISSUE TITLE
Баг с ускорителями (дюп)

### ISSUE THREAD

**Issue by MironLopato** [ZelGimi/industrialupgrade#21]
Нашёл баг, который позволяет из 1 ресурса делать целый стак(64), это работает с новыми предметами, например: Графитовая пластина( если в механизме для крафта стоит много ускорителей в моём случае 11 продвинутых ускорителей, то из ресурсов на 1 штуку делается сразу 64 предмета) так же это работает с жидкостью, например с крафт пластиковой пластины, требуется 1000 mb, то есть 1 капсула кислорода и 1 пластик, но если положить 1 капсулу кислорода и 64 пластика то получиться 64 пластиковой пластины. Если потребуется то я могу сделать видео с багом

**Comment by ZelGimi** [comment]
это давно известно и пофикшено в бете 3.2
