### ISSUE TITLE
Генерация руд

### ISSUE THREAD

**Issue by sedov052** [ZelGimi/industrialupgrade#24]
Я перешел с версии 3.0.3 на 3.1.3 и обнаружил что руды перестали генерироваться как раньше. Вы написали в Changelog, что добавили жилы и удалили старую генерацию. Я стал играть и заметил что руды перестали спавниться, а жилы искать очень трудно и руд с них абсолютно не хватает. Неужели это теперь единственный способ добычи руды, если не считать камешки на поверхности? Я не уверен, может у меня есть какой то баг, но я несколько раз переустанавливал мод и проводил тесты каждый раз в новых мирах, но ничего не менялось.
К слову, спавнятся без жил только рубин, топаз и такие руды.

Это один из моих любимейших модов и я очень хочу продолжить играть в него, заранее спасибо за ответ

**Comment by ZelGimi** [comment]
под камушками всегда будет находиться руда

**Comment by sedov052** [comment]
Спасибо большое за ответ
