### ISSUE TITLE
вопрос про CraftTweaker

### ISSUE THREAD

**Issue by DanChannel** [ZelGimi/industrialupgrade#26]
Есть такой вопрос, при добавлении предмета в крафт "спектральной квантовой брони" у неё есть тег "ID_Item:*" 
данный тег каждый раз разный, и если использовать мод "PackagedExCrafting" то при попытке скрафтить предмет в котором есть "спектральная квантовая броня" то он её не видит.
Данная проблемка не только у этого вида брони.
помогите) а то я туповат, можно это как то исправить?

**Comment by ZelGimi** [comment]
а игнорирования нбт нет? Попробуйте без нбт

**Comment by DanChannel** [comment]
то есть добавлять в крафт 
вот так <industrialupgrade:spectral_chestplate>
а не вот так <industrialupgrade:spectral_chestplate>.withTag({hasID: 1 as byte, canupgrade: 1 as byte, ID_Item: 22})
