### ISSUE TITLE
Баг с хранилищами энергии.

### ISSUE THREAD

**Issue by hDLw08** [ZelGimi/industrialupgrade#27]
Незнаю точно ли это баг, или может я просто чего-то не понимаю, но все же.

 Срафтил Улучшенное МФСУ и захотел поставить туда Модуль RF-Энергия, а он в никакую туда не лезет, написано в подсказке что ПКМ по механизму,
 Жму и ничего не происходит. Написано белым по чёрному, что может хранит Rf-Энергию. 

Возможно требуется модификационая станция?

https://github.com/ZelGimi/industrialupgrade/assets/118069071/e173c4de-6994-4353-a113-febd8a1be947

Вот видео

**Comment by MakandIv** [comment]
Если я не ошибаюсь, больше нет такой функции у хранилищ энергии.

**Comment by fre1q** [comment]
используй конвертер EF/RF

**Comment by hDLw08** [comment]
> используй конвертер EF/RF

Можно поподробней что за конвертер?

 это мод или уже есть в IU?
 Пишу в поиске и нету такого

**Comment by hDLw08** [comment]
> Если я не ошибаюсь, больше нет такой функции у хранилищ энергии.

В подсказке написано "Может хранить Rf-Энергию"

**Comment by fre1q** [comment]
> > используй конвертер EF/RF
> 
> Можно поподробней что за конвертер?
> 
> это мод или уже есть в IU? Пишу в поиске и нету такого

это аддон к iu "Power Utilities"

**Comment by fre1q** [comment]
> > > используй конвертер EF/RF
> > 
> > 
> > Можно поподробней что за конвертер?
> > это мод или уже есть в IU? Пишу в поиске и нету такого
> 
> это аддон к iu "Power Utilities"

но если вдруг энергия не подойдёт (RF), то пробуй другой конвертер FE или TE
