### ISSUE TITLE
Как теперь пользоватся обогатителем.

### ISSUE THREAD

**Issue by Elendron** [ZelGimi/industrialupgrade#30]
Раньше всё было просто, положил предметы, они скрафтились, теперь внизу есть какие то значение радиации, которые нужны. Что это такое и как сделать?

**Comment by ZelGimi** [comment]
![изображение](https://github.com/ZelGimi/industrialupgrade/assets/42618899/fd1c9f65-53c0-4a2f-8f94-206f5c0b3c92)

**Comment by Elendron** [comment]
Понял спасибо
