### ISSUE TITLE
Вопрос: можно ли отключить генерацию руд?

### ISSUE THREAD

**Issue by Chikko5** [ZelGimi/industrialupgrade#31]
У меня установлен GregTech Community Edition, в котором уже есть генерация иридия, платины и тория. Поискал по конфигам, но функции отключения генерации руд этого мода не нашёл.

**Comment by ZelGimi** [comment]
Можете назвать версию мода или версию майнкрафт?

**Comment by Chikko5** [comment]
Minecraft 1.12.2
Мод 1.4.0.2

**Comment by ZelGimi** [comment]
Пока-что нельзя, с новых версий можно будет
