### ISSUE TITLE
Invisible wires and crash

### ISSUE THREAD

**Issue by PandaEzWin** [ZelGimi/industrialupgrade#33]
Если покрасить провода Валиком из ic2, то они станут невидимыми. Также, если поставить сверху на них блок песка (Проверял только его), то он крашнет клиент.

`Видео демонстрация:`
[https://youtu.be/AQUBPO3447o](url)

`Сам crash-report:`
[https://pastebin.com/ibChp1tP](url)

**Comment by ZelGimi** [comment]
Фикс, ждите версию 2.4
