### ISSUE TITLE
Модуль "Стак" не работает

### ISSUE THREAD

**Issue by mrxdata** [ZelGimi/industrialupgrade#33]
Когда я ставлю модуль "стак" в электропечь максимального уровня - она перестает работать
https://github.com/ZelGimi/industrialupgrade/assets/73149744/94696dd9-fb62-45c7-bc61-2d0a5e68c65c

IU version - v2.5.0.26

**Comment by mrxdata** [comment]
Еще модуль Stack не работает в паре с модулем Instant

**Comment by ZelGimi** [comment]
2.5.0.26 не поддерживается, используйте новые версии

**Comment by ZelGimi** [comment]
положите  улучшение хранилище и всё заработает, ибо для 1 операции нужно всё начальное хранилище, а так как у вас 64 , то нужно 64х начального хранилища, то есть нужно минимум докинуть 10к (обычное улучшение хранилища)
