### ISSUE TITLE
Затягиватель уничтожает ресурсы

### ISSUE THREAD

**Issue by mrxdata** [ZelGimi/industrialupgrade#34]
Pulling upgrade уничтожает ресурсы
Когда в механизме установлен затягиватель, и в нем забиты все слоты обработки(стак), когда пройдет цикл и предметов внутри механизма станет 63(неполный стак) pulling upgrade вытягивает 1 слот из хранилища к которому привязан, и если там будет стак предметов то он вытянет 1, а остальные 63 просто пропадут

https://github.com/ZelGimi/industrialupgrade/assets/73149744/9d997d65-24f4-4cc0-a792-c0d0ffe5c0b6

IU version - v2.5.0.26

**Comment by ZelGimi** [comment]
2.5.0.26 не поддерживается, используйте новые версии
