### ISSUE TITLE
Machines work without energy

### ISSUE THREAD

**Issue by PandaEzWin** [ZelGimi/industrialupgrade#34]
Если положить в механизмы определённое количество ускорителей, то они смогут работать без подключения энергии.
(Проверялось на дробителе и электропечи)

Количество:
Обычный ускоритель из ic2 - `48 штук`
Улучшенный ускоритель из iu - `74 штуки`
Продвинутый ускоритель из iu - `113 штук`
Пытался положить меньше, но это не работало. Если положить больше, то работать будет также.

`Видео демонстрация:`
[https://youtu.be/SW_V84r6BJo](url)

**Comment by ZelGimi** [comment]
Фикс, ждите 2.4 версии
