### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Maks-Haswell** [ZelGimi/industrialupgrade#38]
Hello, could you add oil and diesel compatibility from other mods like BuildCraft and Galacticraft to Industrial.Upgrade?

**Comment by ZelGimi** [comment]
Soon I will add integration with liquids from other mods. Thanks for the offer.

**Comment by Maks-Haswell** [comment]
thanks, this will help a lot, and with the refinery, the problem with the textures, they then shine and the same garbage with the drilling rig

**Comment by ZelGimi** [comment]
problem with Optifine

**Comment by Maks-Haswell** [comment]
> problem with Optifine

can this be somehow corrected without removing Optifine?

**Comment by ZelGimi** [comment]
update 2.3
