### ISSUE TITLE
Crash on 3.0.3

### ISSUE THREAD

**Issue by Defflorstor** [ZelGimi/industrialupgrade#4]
Can`t even start MC. There is a crash log, plz help :(

[crash-2023-09-23_13.38.56-client.txt](https://github.com/ZelGimi/industrialupgrade/files/12705832/crash-2023-09-23_13.38.56-client.txt)

**Comment by ZelGimi** [comment]
Crafttweaker script makes crash

**Comment by Defflorstor** [comment]
Oh, kk, will try

**Comment by Defflorstor** [comment]
Oh, really, it works, thx)

**Comment by Defflorstor** [comment]
So, how?
![image](https://github.com/ZelGimi/industrialupgrade/assets/67242805/98bba240-8c11-4d48-9d94-d8c4bbf371b1)
