### ISSUE TITLE
Advanced Oil Refinery

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#40]
When second fluid output is full refinery doesn't stop oil processing, resulting polypropylene loss. Same happens otherwise when first fluid output is full and second isn't. 
![image](https://user-images.githubusercontent.com/16627883/143724354-8a8ca6c1-ca33-4afa-86f4-4fdee16a55b5.png)
![image](https://user-images.githubusercontent.com/16627883/143724360-5f3ef97c-b2e4-40b3-af29-b9dfe376df6e.png)
![image](https://user-images.githubusercontent.com/16627883/143724364-7daced7a-ac20-4673-ab80-0778bdb86b46.png)

My suggestion is something like Mekanism's electrolytic separator, which has buttons to control this behavior
Idle - machine stops when output is full
Dumping excess - removing extra output (current behavior)
Dumping - removing all output
![image](https://user-images.githubusercontent.com/16627883/143724368-e11640c6-190d-4893-a5bb-933cfe23f36a.png)
![image](https://user-images.githubusercontent.com/16627883/143724375-c79903df-4073-4f3a-92eb-3cdc85d67871.png)
Each output is controlled separately

Minecraft 1.7.10
IndustrialUpgrade 2.5.14

**Comment by ZelGimi** [comment]
It is recommended to use capsules

**Comment by ZelGimi** [comment]
The mechanism has been redesigned. For example, if one fluid tank is filled, then the process will not use the main resource
