### ISSUE TITLE
Phase coefficient config for solar panels is ignored

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#41]
As title says - this config is not used so even when it's set to false - panels continue to generate energy depending on sun/moon phase
![image](https://user-images.githubusercontent.com/16627883/143724444-4db2996c-c406-4275-90de-0e328aee0e38.png)
![image](https://user-images.githubusercontent.com/16627883/143724469-f96f81ac-8101-49a3-b58c-4a31331b1d35.png)
![image](https://user-images.githubusercontent.com/16627883/143724472-5fd51e0d-6b61-4610-9b84-5728d0920e2a.png)

Minecraft 1.7.10
IndustrialUpgrade 2.5.14

**Comment by ZelGimi** [comment]
This configuration was disabled in 2.5.10+

**Comment by DarkVen0m** [comment]
Imo you should remove it from config then

**Comment by ZelGimi** [comment]
in 2.5.15 deleted
