### ISSUE TITLE
Tile naming inconsistency

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#42]
Panel Combiner is called like that in game, unifier in config, Sintezator in source code/unlocalized name

![image](https://user-images.githubusercontent.com/16627883/143724606-6c979cdb-c274-405b-9b0b-cc21181edd8a.png)
![image](https://user-images.githubusercontent.com/16627883/143724611-218d5ca6-969b-4fc4-9422-28b3641f892b.png)
![image](https://user-images.githubusercontent.com/16627883/143724697-4062d159-0d5f-4eeb-ab35-225432b44cf2.png)

Minecraft 1.7.10
IndustrialUpgrade 2.5.14

**Comment by ZelGimi** [comment]
in the config will be replaced with a normal name
