### ISSUE TITLE
Cables still burnout with machine explosions turned off

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#43]
When machine is connected with high voltage energy source with low tier cable - cable does burnout even thought explosions are turned off
B:"Enable explosion from mechanisms is on (does not turn off transformer mode) "=false
![2021-11-28_03 52 40](https://user-images.githubusercontent.com/16627883/143724868-5c488532-a963-45a6-a5f9-bfe10c4a1b44.png)
![2021-11-28_03 52 43](https://user-images.githubusercontent.com/16627883/143724869-e1fbc8a7-fd6f-4534-9c3a-7fddb0c0b68f.png)
![2021-11-28_03 52 42](https://user-images.githubusercontent.com/16627883/143724872-0d0e30cc-428a-4250-a11f-bbc0c6bb8cfe.png)

Minecraft 1.7.10
IndustrialUpgrade 2.5.14

**Comment by ZelGimi** [comment]
you have disabled Easy Mode configuration (turns off not to loss energy in cable) through this and the wires burn out

**Comment by DarkVen0m** [comment]
A bit unintuitive but alright. For example I have no problem with having energy loss, but not with explosions as I kinda got used to no explosions/no tier in 1.7.10. And cables burn out is kinda same thing to explosions.
