### ISSUE TITLE
Solar panel modules

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#44]
Solar panel modules' descriptions state that "if module level is equal to or below panel level" and "only one upgrade per slot" in two lines, which can be read as one sentence causing wrong meaning. Like if module level is higher than panel level than it can be multiple modules per slot, while actually higher level modules won't work at all in lower level panels.
"if module level is equal to or below panel level" should be changed to "module level has to be equal to or below panel level"
![image](https://user-images.githubusercontent.com/16627883/143725149-15a31cec-da5e-48b5-ae28-5f6a3baa85db.png)

Minecraft 1.7.10
IndustrialUpgrade 2.5.14

**Comment by MakandIv** [comment]
**Only equal or lower tier module can be placed**
*Only one upgrade per slot**

That's better?

**Comment by DarkVen0m** [comment]
Yeah, looks okay

**Comment by MakandIv** [comment]
OK. Fixed. The next version will have just such a text.
