### ISSUE TITLE
Textures of Advanced Molecular Transformer

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#45]
Textures for some of Advanced Molecular Transformer colors are missing for active/working state.
As well both regular and advanced molecular transformers are dropped when broken in Creative gamemode.

![2021-11-28_05 05 06](https://user-images.githubusercontent.com/16627883/143726135-d59519d9-5196-4408-9c69-7096b8494672.png)
![2021-11-28_05 05 11](https://user-images.githubusercontent.com/16627883/143726134-343a7102-863e-4dbd-974a-723de110aef6.png)

Minecraft 1.7.10
IndustrialUpgrade 2.5.14

**Comment by ZelGimi** [comment]
Fixed. wait 2.5.15
