### ISSUE TITLE
Recipes and Language?

### ISSUE THREAD

**Issue by tong-ge** [ZelGimi/industrialupgrade#46]
No recipes and language files in s12iu03a for 1.12.2?
And,Thorium should not be a gem again!

**Comment by MakandIv** [comment]
Localization files will be added in beta versions. Now while the alpha version. At the moment, there are a lot of problems, in solving which we will often need to adjust the localization files.

In general, as the author (Denfop, aka ZelGimi) gives the go-ahead, I will start writing localizations for both Russian and English.

As far as I know, recipes will also be added in beta versions.

**Comment by tong-ge** [comment]
Also,Uraninite should not be Uranite,Sticks should not be stik.

**Comment by MakandIv** [comment]
> Also,Oredict for Uraninite should not be Uranite,and Sticks should not be stik.
I think a separate question should be opened for this. I am even ready to supplement it, because I have observed not only this. For example, Ahlfeldite. Its OreDict is incorrect.

**Comment by tong-ge** [comment]
Okay,fix Oredicts,Recipes,and l10ns Soon!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月2日(星期四) 晚上11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZelGimi/industrialupgrade] Recipes and Language? (Issue #46)





  
Also,Oredict for Uraninite should not be Uranite,and Sticks should not be stik.
  
I think a separate question should be opened for this. I am even ready to supplement it, because I have observed not only this. For example, Ahlfeldite. Its OreDict is incorrect.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
