### ISSUE TITLE
It is impossible to craft a metal former

### ISSUE THREAD

**Issue by Gamerok200** [ZelGimi/industrialupgrade#49]
To craft a metal former we need 2 invar item casing and 1 iridium item casing(see screenshot 1)
![image](https://user-images.githubusercontent.com/86289101/147101072-cc8bce42-8c14-44e1-a009-0c72ab7248ad.png)
to make casing we need an metal former
![image](https://user-images.githubusercontent.com/86289101/147101157-54d2f7f8-80aa-48c9-8f41-29c36556c4aa.png)
that is, now there is no way to get neither metal former nor casing in any other way

More. In crafting we need to make 3 different machines.
![image](https://user-images.githubusercontent.com/86289101/147101354-2d396b96-3eef-4bcb-88ce-a6fcab7fa8c8.png)
For example extruder, maybe this machine should craft but no ricipe are present.
And have a bug in the recipe of all of the 3 machines
![image](https://user-images.githubusercontent.com/86289101/147101658-7408ed51-69da-4ff8-a388-f9873e0111f9.png)
We insert all needed items for craft and see a reuslt. When we take that block the hammer lose 1 durability and rest
![image](https://user-images.githubusercontent.com/86289101/147101772-2833512f-ccc9-4b88-9153-e782b96bb611.png)
And if u need to craft 2 or more metal former logit that u need to produce 3,6 or more+3 hammers to do. It would be right not to lose them durability, but to fully use them in crafting

**Comment by ZelGimi** [comment]
Use item with metadata 0.

**Comment by Gamerok200** [comment]
And the fact that there are no recipes in 3 machines is a temporary flaw?

**Comment by ZelGimi** [comment]
Strange, but all three machines work fine.
