### ISSUE TITLE
CraftTweaker support?

### ISSUE THREAD

**Issue by Rongmario** [ZelGimi/industrialupgrade#50]
Is there any CraftTweaker support built into the mod at the moment? And if there are, what are the syntaxes?

**Comment by ZelGimi** [comment]
Yes, what mechanism do you need?

**Comment by senfun** [comment]
molecular transformer/advanced  molecular transformer  
Circuit Manufacturer?

**Comment by ZelGimi** [comment]
advanced molecular transformer
ADD:
mods.industrialupgrade.MolecularTransformer.addRecipe(IItemStack output, IIngredient container, IIngredient fill, energy);
REMOVE:
mods.industrialupgrade.MolecularTransformer.removeRecipe(IItemStack output);
molecular transformer
ADD:
mods.industrialupgrade.MolecularTransformer.addRecipe(IItemStack output, IIngredient ingredient, energy);
REMOVE:
mods.industrialupgrade.MolecularTransformer.removeRecipe(IItemStack output);
Circuit Manufacturer
ADD:
mods.industrialupgrade.GenMicrochip.addRecipe(IItemStack output, IIngredient container, IIngredient fill, IIngredient fill1, IIngredient fill2, IIngredient fill3, temperature);
REMOVE:
mods.industrialupgrade.GenMicrochip.removeRecipe(IItemStack output);

**Comment by senfun** [comment]
thanks!
