### ISSUE TITLE
Can't crafting circuit 

### ISSUE THREAD

**Issue by arrester-002** [ZelGimi/industrialupgrade#51]
I can't make a circuit for circuit crafter
(Strictly speaking, Nano Capacitor cannot be made.)

**Comment by ZelGimi** [comment]
goow work
![изображение](https://user-images.githubusercontent.com/42618899/147498551-5ff0d242-21e6-46eb-b54e-b281a927b91e.png)
![изображение](https://user-images.githubusercontent.com/42618899/147498563-1e349ab3-61b0-4b29-8c5b-eb6407771d15.png)

**Comment by arrester-002** [comment]
![2021-12-28_13 00 06](https://user-images.githubusercontent.com/73302625/147526636-1d4fe09e-79a2-4ce6-b0b2-210eca97bdaa.png)
Do not working

**Comment by arrester-002** [comment]
Do not working
![2021-12-28_13 02 49](https://user-images.githubusercontent.com/73302625/147526680-c67d29b7-59f2-4c31-b304-37979d5914d5.png)

**Comment by MakandIv** [comment]
Is UniDict installed? It's just that it breaks aluminum because of other non-end interchangeable resources.

**Comment by arrester-002** [comment]
Do not installed

**Comment by arrester-002** [comment]
not installed

**Comment by arrester-002** [comment]
UniDict installed, but don't worked

**Comment by MakandIv** [comment]
No, on the contrary, he makes it worse). Can you throw off the list of mods that you have installed? I'll try to reproduce the error.

**Comment by arrester-002** [comment]
Lists
![2021y12m28d_160957671](https://user-images.githubusercontent.com/73302625/147538660-b0c3261f-889d-4326-b135-3f457e42ad2c.jpg)
![2021y12m28d_160750934](https://user-images.githubusercontent.com/73302625/147538667-94373e93-097d-4dfa-aace-294ad38cd216.jpg)
![2021y12m28d_160811579](https://user-images.githubusercontent.com/73302625/147538668-9225856a-75e1-4963-8e47-9cd20d1ea6d1.jpg)
![2021y12m28d_160822996](https://user-images.githubusercontent.com/73302625/147538671-deb9bd0f-a97c-480b-ba9c-7e385609329c.jpg)
![2021y12m28d_160837895](https://user-images.githubusercontent.com/73302625/147538674-6056fd88-d0c0-482b-9031-0f1a4a250b4f.jpg)
![2021y12m28d_160853210](https://user-images.githubusercontent.com/73302625/147538675-d4d840f4-d8cb-4a46-bfb0-e372ef632bd3.jpg)
![2021y12m28d_160911602](https://user-images.githubusercontent.com/73302625/147538676-72f41465-aeaa-4fef-ad06-2cc9efbf9862.jpg)
![2021y12m28d_160930307](https://user-images.githubusercontent.com/73302625/147538678-3822a9fe-ad1b-47bb-ab3b-da05650e980c.jpg)

**Comment by ZelGimi** [comment]
you haven't connected heaters with the IU near the mechanism

**Comment by arrester-002** [comment]
Is it a problem within IU?

**Comment by arrester-002** [comment]
crafted
