### ISSUE TITLE
crash IUCore incompatible with AdvancedSolarPanels

### ISSUE THREAD

**Issue by Armagedon13** [ZelGimi/industrialupgrade#52]
https://pastebin.com/azizm1KC

**Comment by MakandIv** [comment]
The IU version for 1.12.2 is temporarily incompatible with ASP. It will be fixed soon. Anyway, IU has all the same features as ASP.

**Comment by Armagedon13** [comment]
oh so if i uninstall ASP and keep only IU i have all stuff from ASP in IU?

**Comment by MakandIv** [comment]
Yes, there should be. But it will be fixed soon, so if something is missing from the ASP, you can return it.

**Comment by Armagedon13** [comment]
ok im gonna use IU for testing in my world thanks

**Comment by Armagedon13** [comment]
ok, the new version solved the crash thanks for your time 😃
