### ISSUE TITLE
Batbox only accept oak wood planks

### ISSUE THREAD

**Issue by Armagedon13** [ZelGimi/industrialupgrade#54]
industrial upgrade:
![image](https://user-images.githubusercontent.com/12619078/147809491-674e7a81-3d94-472a-9990-87bee1cbe560.png)
industrial craft 2:
![image](https://user-images.githubusercontent.com/12619078/147809511-625ad971-5763-465f-881d-8943433caf50.png)

**Comment by ZelGimi** [comment]
fixed

**Comment by ZelGimi** [comment]
Download with curseforge 2.2 again
