### ISSUE TITLE
Conflict with IndustrialCraft2

### ISSUE THREAD

**Issue by border999** [ZelGimi/industrialupgrade#55]
https://gist.github.com/border999/b1e928aa95c012a2bb5b0635a52a22b9

**Comment by ZelGimi** [comment]
Old version of the mod, you should update to the current 2.2

**Comment by border999** [comment]
https://gist.github.com/border999/ca402066ad5c416fedbdc2bc584c0f36

**Comment by border999** [comment]
same issue. IndustrialUpgrade-1.12.2-2.2 still has the same issue

**Comment by ZelGimi** [comment]
Send me a crash log from version 2.2, not from the first snapshot

**Comment by border999** [comment]
the second link IS from version 2.
[crash-2022-01-09_09.02.53-client.txt](https://github.com/ZelGimi/industrialupgrade/files/7835755/crash-2022-01-09_09.02.53-client.txt)

**Comment by border999** [comment]
![Screenshot 2022-01-09 093111](https://user-images.githubusercontent.com/11824584/148697761-f47c0396-257c-49a1-a0eb-14c804ed20c3.jpg)

**Comment by ZelGimi** [comment]
![изображение](https://user-images.githubusercontent.com/42618899/148697796-837be4ee-d623-4f32-a800-35d5e0a8c355.png)
it's not 2.2

**Comment by ZelGimi** [comment]
You have 2 version
![изображение](https://user-images.githubusercontent.com/42618899/148697936-c337a2ab-fc02-4504-81c8-1c85175e57b7.png)
and
![изображение](https://user-images.githubusercontent.com/42618899/148697938-be2c3ff0-80e0-4cc4-8b6f-69dfe5c02cdc.png)

**Comment by ZelGimi** [comment]
delete s12iu01a version

**Comment by border999** [comment]
jesus, no wonder. Why would THAT be the name it put when I got it off curseforge. Also, why didn't it trigger the (multiple of the same mod) alert

**Comment by ZelGimi** [comment]
Because this mod in s12iu01a was called super solar panels, and after it IndustrialUpgrade, but it's strange that it did not replace it

**Comment by border999** [comment]
Well that's that issue resolve. Now onto a startup crash with Immersive Intelligence. Have a nice day and I thank you for your assistance.

**Comment by ZelGimi** [comment]
)
