### ISSUE TITLE
 IndustrialCraft2 power storage box

### ISSUE THREAD

**Issue by WatermelonEmperor** [ZelGimi/industrialupgrade#58]
I want to make MFE of IndustrialCraft 2,but only get MFE of IndustrialUpgrade.
![image](https://user-images.githubusercontent.com/72055913/150929382-1cbcf944-51e9-460e-bb92-424b56cb3eb1.png)
![image](https://user-images.githubusercontent.com/72055913/150930026-f648d19b-cbf8-438d-9d6f-4c7ba673a6dd.png)
![QQ录屏20220125151654 00_00_00-00_00_15](https://user-images.githubusercontent.com/72055913/150930474-67f91a96-8f7e-41d6-b4a7-effb5cc944c4.gif)

How can I modify the configuration so that I can get the MFE of IndustrialCraft？
![image](https://user-images.githubusercontent.com/72055913/150925362-f82108a0-2153-4788-8192-321b5a1ebe46.png)

**Comment by ZelGimi** [comment]
Crafting has been completely removed in 2.3, you only need to craft energy storage from IU

**Comment by ZelGimi** [comment]
update 2.3 fixed
