### ISSUE TITLE
[1.12.2]Ex Nihilo integration BUG

### ISSUE THREAD

**Issue by RuiXuqi** [ZelGimi/industrialupgrade#61]
![image](https://user-images.githubusercontent.com/90179819/151651629-d42c52bc-0361-4ac1-990e-7acc10c4a874.png)
The Ex Nihilo: Creatio doesn't have these items.
The items are redundant.
Please remove them.
They have lang BUG too.

**Comment by MakandIv** [comment]
Can you show what the "BUG" is?

**Comment by RuiXuqi** [comment]
It's not a bug, it's a typo

**Comment by MakandIv** [comment]
Can you show me the typo?

**Comment by RuiXuqi** [comment]
I mean the title is a typo

**Comment by MakandIv** [comment]
I get it, I just don't see it. Can you show the title itself with a typo?

**Comment by RuiXuqi** [comment]
There are some superfluous items in the integration.
They don't fit the original
