### ISSUE TITLE
Crash Latest Version

### ISSUE THREAD

**Issue by Petrol12** [ZelGimi/industrialupgrade#64]
The mod has crashed. Latest version of IndustrialUpgrade: 1.12.2-2.3.4.
https://pastebin.com/nrQB2Wx0

**Comment by ZelGimi** [comment]
I know about the error and there will be a fix soon, wait for 2.3.5. This error was due to the fact that one developer of some mod wanted to be on two chairs, but did not think it was bad

**Comment by Petrol12** [comment]
Thank You
