### ISSUE TITLE
Electric Wire doesnt connect Physicaly to Reactor Turbine Mod.

### ISSUE THREAD

**Issue by xXIchTuDirWehXx** [ZelGimi/industrialupgrade#66]
Case:
After Installing: Industrial Upgrade Any Wire does not connect with Wire Physicaly to a Reactor Turbine after its Active, Intrestingly enough Producing Energy works.
Physical Connection Work to Reactor Turbines after Removal of the Industrial Upgrade Mod.
![2022-02-19_16 13 16](https://user-images.githubusercontent.com/84048089/154806792-7a4f370d-de85-4820-a57b-a143ac6872d4.png)
The Mod i talked about:
https://www.curseforge.com/minecraft/mc-mods/reactor-turbines-mod-for-ic2

**Comment by ZelGimi** [comment]
what version of the mod (IU)?

**Comment by xXIchTuDirWehXx** [comment]
> what version of the mod (IU)?
Latest Build.
[1.12.2-2.3.5](https://www.curseforge.com/minecraft/mc-mods/industrial-upgrade/files/3645167)

**Comment by ZelGimi** [comment]
will be fixed in 2.3.6

**Comment by xXIchTuDirWehXx** [comment]
> will be fixed in 2.3.6

Nice to hear it. Thanks for doing Nice work on a Extension of IC2! :)

**Comment by ZelGimi** [comment]
fixed
