### ISSUE TITLE
Advanced Molecular Machines and Modify Module

### ISSUE THREAD

**Issue by fengsui9527** [ZelGimi/industrialupgrade#67]
Advanced molecular mechanisms make modification modules: accumulate energy will collapse the client, directly make the client unresponsive!!! Advanced molecular mechanisms make modification modules: damage (bow) will crash the server, directly restart the server!!!

**Comment by fengsui9527** [comment]
in 2.3.5

**Comment by ZelGimi** [comment]
Fixed, wait 2.4

**Comment by ZelGimi** [comment]
fixed
