### ISSUE TITLE
Нужны десятки тысяч иридия в начале...............

### ISSUE THREAD

**Issue by Mannsio** [ZelGimi/industrialupgrade#75]
Из-за того, что требуется 4 ядра на каждое новое, то есть умножается на 4 КАЖДОЕ ядро. И по итогу, для гена материи нужно 16-20к иридиевых слитков, я уж молчу про то сколько это будет делаться.... Что делать?

**Comment by ZelGimi** [comment]
Используйте аддоны или другие механизмы для добычи слитков
