### ISSUE TITLE
advanced molecular crasher

### ISSUE THREAD

**Issue by ndrlptn** [ZelGimi/industrialupgrade#80]
game crashes after trying to create night vision module in advanced molecular converter
![Новый точечный рисунок](https://user-images.githubusercontent.com/105172985/167313068-4ea1334a-cb19-4cc9-9b05-f5acc4f461f0.jpg)
t
hen game will crash if try to use any mechanism

crash report:

[crash-2022-05-09_00.52.46-server.txt](https://github.com/ZelGimi/industrialupgrade/files/8647670/crash-2022-05-09_00.52.46-server.txt)

**Comment by ZelGimi** [comment]
Fixed, use build's mod in github
