### ISSUE TITLE
recipe issue with IU

### ISSUE THREAD

**Issue by SieIin** [ZelGimi/industrialupgrade#81]
![image](https://user-images.githubusercontent.com/76398137/167868474-8f08ae90-f4c7-45db-aa14-92fbd00c87e5.png)
![image](https://user-images.githubusercontent.com/76398137/167868493-1170373b-e742-4c88-b6b4-f0df881e68f0.png)
When using IU the cost of the ingot plate is printed as 9 in JEI. but others showing normal

**Comment by ZelGimi** [comment]
version

**Comment by SieIin** [comment]
sorry, was there form for issue?
IU version is 1.12.2 2.3.5

**Comment by ZelGimi** [comment]
check build 17 2.4

**Comment by SieIin** [comment]
tungsten one has been solved but iridium, invar, manganese still causing problem

**Comment by ZelGimi** [comment]
very strange

**Comment by SieIin** [comment]
tried remove IU plate from oredic but the problem moved to another one which have same oredic
