### ISSUE TITLE
Support for Flux Networks

### ISSUE THREAD

**Issue by WatermelonEmperor** [ZelGimi/industrialupgrade#82]
FluxNetworks can build Wireless Energy Networks.But in IndustrialUpgrade 2.3 and later versions,  FluxNetworks cannot be used normally.Is support planned?

**Comment by ZelGimi** [comment]
check build 17 2.4

**Comment by WatermelonEmperor** [comment]
![image](https://user-images.githubusercontent.com/72055913/168035293-6cf5a6a7-b57e-47a5-b4fc-18f53c74d2a9.png)
I installed industrialcraft-2-2.8.221-ex112build#17, and industrialcraft-2-2.8.221-ex112 and FluxNetworks-1.12.2-4.1.1.34
FluxNetworks can only be used normally in IndustrialUpgrade 2.2 and earlier versions.

> 检查构建 17 2.4

**Comment by WatermelonEmperor** [comment]
https://user-images.githubusercontent.com/72055913/168041712-99a5c41b-7349-416f-a82d-49c06785d80b.mp4
[crash-2022-05-12_17.37.38-server.txt](https://github.com/ZelGimi/industrialupgrade/files/8676886/crash-2022-05-12_17.37.38-server.txt)

It have a bug.
If I connect the Flux Plug to 6 tier and higher generator,the game will collapse.

**Comment by ZelGimi** [comment]
throw off the crash log

**Comment by WatermelonEmperor** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 5/12/22 5:37 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at aroma1997.uncomplication.enet.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:514)
	at aroma1997.uncomplication.enet.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:48)
	at aroma1997.uncomplication.enet.EventHandler.tick(EventHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_97_EventHandler_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1865658008 bytes (1779 MB) / 4429185024 bytes (4224 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version       | Source                              | Signature                                |
	|:------ |:------------------ |:------------- |:----------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2        | minecraft.jar                       | None                                     |
	| LCHIJA | mcp                | 9.42          | minecraft.jar                       | None                                     |
	| LCHIJA | FML                | 8.0.99.99     | forge-1.12.2-14.23.5.2859.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2859  | forge-1.12.2-14.23.5.2859.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ic2                | 2.8.221-ex112 | industrialcraft-2-2.8.221-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | sonarcore          | 5.0.19        | sonarcore-1.12.2-5.0.19-20.jar      | None                                     |
	| LCHIJA | fluxnetworks       | 4.1.0         | FluxNetworks-1.12.2-4.1.1.34.jar    | None                                     |
	| LCHIJA | industrialupgrade  | 2.4_build_17  | IndustrialUpgrade-1.12.2-2.4.jar    | None                                     |
	| LCHIJA | powerutils         | 1.2           | IndustrialUpgrade-1.12.2-2.4.jar    | None                                     |
	| LCHIJA | quantum_generators | 1.2           | IndustrialUpgrade-1.12.2-2.4.jar    | None                                     |
	| LCHIJA | simplyquarries     | 1.3           | IndustrialUpgrade-1.12.2-2.4.jar    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['aWatermelonKing'/146, l='New World', x=-757.01, y=4.00, z=-1796.77]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

> 扔掉崩溃日志

**Comment by ZelGimi** [comment]
fixed, wait build 18
