### ISSUE TITLE
reactor turn into error block when restart the game

### ISSUE THREAD

**Issue by SieIin** [ZelGimi/industrialupgrade#84]
![image](https://user-images.githubusercontent.com/76398137/168479739-6bee2ec6-8ef4-4bdc-97bb-0d54e7e0cab2.png)
![image](https://user-images.githubusercontent.com/76398137/168479748-4f5fa9b2-ef1f-4f40-8fb2-767ab6571984.png)
iu version is build 19

**Comment by ZelGimi** [comment]
Can you post a video of this process? Checking for such a bug - it is not there

**Comment by SieIin** [comment]
https://youtu.be/ghre7M9xXYA
https://youtu.be/4uZ2TwHz9nI

sorry for too late responding.
the stupid mail have not notised me.
the link have this process. hope this will solve problem.

**Comment by ZelGimi** [comment]
try 2.4 build 25
