### ISSUE TITLE
 Couldn't load advancement industrialupgrade:main/sin_core: Task Advancement{parentId=industrialupgrade:main/pro_core, display=net.minecraft.advancements.DisplayInfo@2d08f87e, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={mine=net.minecraft.advancements.Criterion@27d10281}, requirements=[[mine]]}

### ISSUE THREAD

**Issue by juzhijian** [ZelGimi/industrialupgrade#85]
Couldn't load advancement industrialupgrade:main/sin_core: Task Advancement{parentId=industrialupgrade:main/pro_core, display=net.minecraft.advancements.DisplayInfo@2d08f87e, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={mine=net.minecraft.advancements.Criterion@27d10281}, requirements=[[mine]]}

**Comment by ZelGimi** [comment]
check this bug in 2.4 build 19

**Comment by ZelGimi** [comment]
fixed
