### ISSUE TITLE
[1.12.2-2.3.5]When it is installed with Avaritia, it produces strange bugs

### ISSUE THREAD

**Issue by tanyuguai** [ZelGimi/industrialupgrade#86]
When you mine the "Molecular Transformer" with the "World Breaker" of the Avaritia mod, you get 8 drops! Very amazing yield.
Not just the "Molecular Transformer", most blocks produce 4-8 drops!

**Comment by ZelGimi** [comment]
Check bug in 2.4 build 19

**Comment by tanyuguai** [comment]
I just tried version 2.4 and the bug still exists.

**Comment by ZelGimi** [comment]
Having checked other tools, not only this mod on molecular transformer, I can say that the bug is observed only with this item

**Comment by tanyuguai** [comment]
I haven't encountered this bug yet with other tools, only when using World Breaker.

**Comment by tanyuguai** [comment]
Oil Refinery also have this bug

**Comment by tanyuguai** [comment]
and Liquid Tank
sintezator_item
converter_solid
Core Search Drilling Rig
combiner_solidmatter
petrol_quarry_item
adminpanel_item
upgrade_block_item

**Comment by ZelGimi** [comment]
So, I can’t do anything else, with other tools (I also talked about other mods in which the area is NxM), then there is no such bug with such items

**Comment by tanyuguai** [comment]
But I use it to destroy the title block of other mods, and the number of drops is normal. Only your mod has a problem, this phenomenon is very strange...

**Comment by tanyuguai** [comment]
I discovered this problem last year, when only the "Molecular Transformer" had bugs, so I haven't come to feedback, but now a lot of things have bugs. At that time your mod was called "super solar panels".

**Comment by tanyuguai** [comment]
I'm pretty sure it's only your mod that has this bug since I played last year....

**Comment by tong-ge** [comment]
Features,features,features...They are features...

**Comment by ZelGimi** [comment]
I understand logically, if a bug drop in another mod then this is his problem, on the one hand, yes, but if everything is fine with other things with other mods, then the problem means in this instrument that breaks them

**Comment by Dreeam-qwq** [comment]
Seems only some blocks of IU have this bug. Blocks of other some of mods will drop normal number of items when break by the "World Breaker"

**Comment by ZelGimi** [comment]
this bug is not on the IU side, it needs to be fixed in Avaritia
