### ISSUE TITLE
Spectral Cable Dupe

### ISSUE THREAD

**Issue by Dreeam-qwq** [ZelGimi/industrialupgrade#87]
Bug Description
Player can dupe Spectral Cable of industrial upgrade.

Steps to Reproduce

- Install Industrial Upgrade mod for 1.12.2
- Place a Spectral Cable and break it
- Don't pick up the item and place another Spectral Cable and then break it
- Pick up two items
- Then place it and break it again
- You get 2 times of Spectral Cable.

Additional Server Info
1.12.2
Mod version: Industral Upgrade 2.3.5
Server: mohist-1.12.2-321-server

**Comment by vladimirshefer** [comment]
could not replroduce on 1.12.2+2.3.5 on my own server.

should i place then on the same block?

@Dreeam-qwq

**Comment by ZelGimi** [comment]
The bug is executed in some cases, in new versions (build, beta, release candidate) - it is not

**Comment by ZelGimi** [comment]
fixed a long time ago
