### ISSUE TITLE
How to remove GenMicrochip recipes with CraftTweaker

### ISSUE THREAD

**Issue by Kouchya** [ZelGimi/industrialupgrade#88]
I'm using IndustrialUpgrade-2.3.5 and CraftTweaker-4.1.20. I want to remove some recipes from the circuit manufacturer, but when I tried mods.industrialupgrade.GenMicrochip.removeRecipe method in CraftTweaker, it came out the "No such static member" error. I checked the source code only to find an addRecipe method, and so does some other machines like AlloySmelter and Enrich. Is there any way to remove recipes from these machines?

**Comment by ZelGimi** [comment]
use IU 2.4 build №22

**Comment by Kouchya** [comment]
It works now. Thanks a lot!
