### ISSUE TITLE
Config key has no effect when changed: "Solar panels will generate energy using phase Sun or Moon"

### ISSUE THREAD

**Issue by vladimirshefer** [ZelGimi/industrialupgrade#89]
I have found these lines in config file, but when i change it to false, then nothing happens.
```
experimental {
    B:"Solar panels will generate energy using phase Sun or Moon"=false
}
```
Environment:
- Minecraft 1.12.2
- Industrial Upgrade 2.3.5

Steps to reproduce:
1. Change value to false
2. Restart server.

Expected behaviour:
- Solar panels do not change the production rate during the day/night.

Actual behaviour:
- Solar panels continue vary the output from 0 to <solar panel max output> during the day/night.

**Comment by ZelGimi** [comment]
Будет убрано через не действительность

**Comment by ZelGimi** [comment]
Will be removed due to invalid

**Comment by ZelGimi** [comment]
in 2.4RC3 fixed
