### ISSUE TITLE
Spectral solar panels have twice lower max output than decraled.

### ISSUE THREAD

**Issue by vladimirshefer** [ZelGimi/industrialupgrade#90]
Spectral solar panel declares generation up to 1.27K EU/t, but actually it generates up to ~600 EU/t at the middle of the day.
When I destroy this solar panel and put it back then for some time the output becomes normal (~1.2K EU/t).

![image](https://user-images.githubusercontent.com/23248545/173241197-58da3773-3c8c-4d76-8367-5b725fe402f0.png)

at mid of the day:
![image](https://user-images.githubusercontent.com/23248545/173241274-2c485b6c-5530-4ebf-8eb8-c900903b8f3b.png)

after destroying and set again:
![image](https://user-images.githubusercontent.com/23248545/173241244-775cdc53-fbf9-420d-b16f-e536ac154de7.png)

At the miidle of the night this paned outputs wtice lower output than declared (300EU/t instead of 600UE/t)
![image](https://user-images.githubusercontent.com/23248545/173241483-07a8ec19-8caa-49f3-9905-38a78517a176.png)

Environment:
- Minectaft 1.12.2
- Industrial Upgrade 2.3.5

Steps to reproduce:
1. Place the Spectral solar panel
2. Wait undefined amount of time (???)
3. Wait for the mid of the day
4. Check the EU output.

Actual behaviour:
Solar panel outputs whice lower EU/t than declared (~600 EU/t instead of ~1200EU/t)

Expected behaviour:
Solar panel outputs declared EU/t (1.2K EU/t)

**Comment by ZelGimi** [comment]
1. Solar panels have pollution that can affect the generation of panels
2. The generation of panels is dependent on the angle of the Sun or Moon, use the module for phases

**Comment by vladimirshefer** [comment]
yes, thank you, when i applier "cleaner" to solar panela, then problem has gone.
