### ISSUE TITLE
Add liquid nuclear reactor.

### ISSUE THREAD

**Issue by Pilad** [ZelGimi/industrialupgrade#95]
Add nuclear reactors the ability to operate as liquid reactors.

**Comment by ZelGimi** [comment]
Will be added in 3.0

**Comment by Pilad** [comment]
> Will be added in 3.0

I take it this version is no longer available?

**Comment by ZelGimi** [comment]
It is available but alpha, so far the base (foundation) has been made, and already with the next alpha something that everyone and I have been waiting for a long time will begin.  the variety that everyone was waiting for
