### ISSUE TITLE
Bug: Electrolizer burns stack of anods/cathods at once

### ISSUE THREAD

**Issue by vladimirshefer** [ZelGimi/industrialupgrade#96]
If i use pipe/bus to put anods/cathods to the electrolizer, then all of them are used at oce without extra output.

![image](https://user-images.githubusercontent.com/23248545/175833018-38770726-59c3-4333-bb9f-0774b2af6a6b.png)

Steps to reproduce:
1. Set the Electrolizer
2. Fill with water.
3. Attach the pipe and push the anods/cathods into Electrolizer

Expected behaviour:
1. Electrolizer does not allow the stack of anods/cathods to be pushed into it
OR
1. Electrolizer produces more oxygen and hydroden depending of the amount of anods/cathods in the slot.

Actual behaviour:
1. Electrolizer burns the whole stack of anods/catchods at once as if is were only one.

**Comment by vladimirshefer** [comment]
This bug prevents me from oxygen/hydrogen crafting automatization

**Comment by vladimirshefer** [comment]
I have found a workaround:
You could use a vanilla minecraft hopper to push items to the Electrolizer. It prevents cathods/anods from stacking in Electrolizer.

**Comment by ZelGimi** [comment]
fixed
