### ISSUE TITLE
Chinese Translation submission

### ISSUE THREAD

**Issue by Oldmemory1** [ZelGimi/industrialupgrade#98]
https://pastebin.com/vxVrWmtu 
If you can not visit pastebin,try the following website:
https://github.com/Oldmemory1/Industrialupgrade1.7.10-chinese-translation
Chinese translation(zh_CN.lang) for Industrial Upgrade 1.7.10-2.5.21
I am a player from China,who is interested in this mod,I hope my chinese translation can be accepted. :)

**Comment by MakandIv** [comment]
I added zh_cn.lang under your authorship with IULU. In the next version for 1.7.10, localization will be included in the mod. You can also check the change of the English localization to bring the Chinese localization to the new version faster.
https://github.com/MakandIv/industrial-upgrade-localizations
