### ISSUE TITLE
IC2 armor not charging your mod's tools

### ISSUE THREAD

**Issue by idSnail** [ZelGimi/industrialupgrade#99]
![Screenshot_2](https://user-images.githubusercontent.com/108696380/177216745-eab4ed9e-9301-48de-9417-f15361fb9940.png)
![Screenshot_1](https://user-images.githubusercontent.com/108696380/177216748-08244db0-e759-4944-9c94-53e8ca63fac5.png)

**Comment by ZelGimi** [comment]
By default, quantum armour does not charge items in the inventory, but exist method, that executes when the item is discharged, and charge energy instruments from armour. You should use chargers to charge tools

**Comment by ZelGimi** [comment]
Perhaps I will insert such a method in RC4
